DROP TABLE BED_OCC_FACT CASCADE CONSTRAINTS;
DROP TABLE TIME_DIME CASCADE CONSTRAINTS;
DROP TABLE WARD_DIME CASCADE CONSTRAINTS;
DROP TABLE CARE_CENTRE_DIME CASCADE CONSTRAINTS;


CREATE TABLE BED_OCC_FACT (
	BED_OCC_FACT_ID NUMBER(4) NOT NULL,
	WARD_ID NUMBER(4) NULL,
	TIME_ID NUMBER(4) NULL,
	CARE_CENTRE_ID NUMBER(4) NULL,
	TOTAL_OCCUPIED_BEDS NUMBER(3) NULL,
	PRIMARY KEY (BED_OCC_FACT_ID)
);

CREATE TABLE TIME_DIME (
	TIME_ID NUMBER(4) NOT NULL,
	MONTH NUMBER(2) NULL,
	YEAR NUMBER(4) NULL,
	PRIMARY KEY (TIME_ID)
);

CREATE TABLE WARD_DIME (
	WARD_ID NUMBER(4) NOT NULL,
	WARD_NAME VARCHAR2(20) NULL,
	PRIMARY KEY (WARD_ID)
);

CREATE TABLE CARE_CENTRE_DIME (
	CARE_CENTRE_ID NUMBER(4) NOT NULL,
	CARE_CENTRE_NAME VARCHAR2(20) NULL,
	START_DATE DATE NULL,
	END_DATE DATE NULL,
	ISCURRENT VARCHAR2(4) NULL,
    CARE_CENTRE_N_ID VARCHAR2(8) NULL,
	PRIMARY KEY (CARE_CENTRE_ID)
);

ALTER TABLE BED_OCC_FACT ADD CONSTRAINT BED_OCC_FACT_DIM_to_DEPT_DIME FOREIGN KEY(WARD_ID) REFERENCES WARD_DIME(WARD_ID);
ALTER TABLE BED_OCC_FACT ADD CONSTRAINT BED_OCC_FACT_DIM_to_TIME_DIME FOREIGN KEY(TIME_ID) REFERENCES TIME_DIME(TIME_ID);
ALTER TABLE BED_OCC_FACT ADD CONSTRAINT BED_OCC_FACT_DIM_to_CARE_CENTRE_DIME FOREIGN KEY(CARE_CENTRE_ID) REFERENCES CARE_CENTRE_DIME(CARE_CENTRE_ID);

DROP SEQUENCE TIME_ID_SEQU;
DROP SEQUENCE WARD_ID_SEQU;
DROP SEQUENCE CARE_CENTRE_ID_SEQU;
DROP SEQUENCE BED_OCC_FACT_ID_SEQU;

CREATE SEQUENCE TIME_ID_SEQU
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    MINVALUE 1;

CREATE SEQUENCE WARD_ID_SEQU
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    MINVALUE 1;

CREATE SEQUENCE CARE_CENTRE_ID_SEQU
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    MINVALUE 1;

CREATE SEQUENCE BED_OCC_FACT_ID_SEQU
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    MINVALUE 1;
