SELECT CARE_CENTRE_ID, CARE_CENTRE_NAME FROM NYR_CARE_CENTRE;
SELECT CARE_ID, CARE_CENTRE_NAME FROM WYR_CARE_CENTRE;

DROP TABLE S1_STAGE_CARE_CENTRE;
CREATE TABLE S1_STAGE_CARE_CENTRE AS SELECT CARE_CENTRE_ID, CARE_CENTRE_NAME FROM NYR_CARE_CENTRE;

ALTER TABLE S1_STAGE_CARE_CENTRE 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_CARE_CENTRE SET DATASOURCE = 'NYR';

INSERT INTO  S1_STAGE_CARE_CENTRE (SELECT CARE_ID, CARE_CENTRE_NAME, 'WYR' FROM WYR_CARE_CENTRE);

SELECT * FROM S1_STAGE_CARE_CENTRE;
DROP TABLE S2_STAGE_CARE_CENTRE;
CREATE TABLE S2_STAGE_CARE_CENTRE AS 
    SELECT ( CC.DATASOURCE || '_' || CC.CARE_CENTRE_ID) AS CARE_CENTRE_N_ID,CARE_CENTRE_ID, CC.CARE_CENTRE_NAME 
        FROM S1_STAGE_CARE_CENTRE CC;
SELECT * FROM S2_STAGE_CARE_CENTRE;
UPDATE S2_STAGE_CARE_CENTRE SET CARE_CENTRE_N_ID = ( 'C'||'_'|| CARE_CENTRE_N_ID);

SELECT WARD_ID, WARD_NAME, CARE_CENTRE_ID FROM NYR_WARD;
SELECT CARE_ID, WARD_NO, WARD_NAME FROM WYR_WARD;

DROP TABLE S1_STAGE_WARD;
CREATE TABLE S1_STAGE_WARD AS SELECT WARD_ID, WARD_NAME, CARE_CENTRE_ID FROM NYR_WARD;

ALTER TABLE S1_STAGE_WARD 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_WARD SET DATASOURCE = 'NYR';

INSERT INTO  S1_STAGE_WARD (SELECT WARD_NO, WARD_NAME, CARE_ID, 'WYR' FROM WYR_WARD);

SELECT * FROM S1_STAGE_WARD;

SELECT BED_ID, WARD_ID FROM NYR_BED;
SELECT BED_NO, WARD_NO FROM WYR_BED;

DROP TABLE S1_STAGE_BED;
CREATE TABLE S1_STAGE_BED AS SELECT BED_ID, WARD_ID FROM NYR_BED;

ALTER TABLE S1_STAGE_BED 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_BED SET DATASOURCE = 'NYR';

ALTER TABLE S1_STAGE_BED MODIFY BED_ID NUMBER(5,0);
ALTER TABLE S1_STAGE_BED MODIFY WARD_ID NUMBER(5,0);

INSERT INTO  S1_STAGE_BED (SELECT BED_NO, WARD_NO, 'WYR' FROM WYR_BED);

SELECT * FROM S1_STAGE_BED;

SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE FROM NYR_ADMISSION;
SELECT RESERVATION_ID, BED_NO FROM WYR_BEDASSIGNED;
SELECT RESERVATION_ID, ADMISSION_DATE FROM WYR_RESERVATION;

DROP TABLE S1_STAGE_ADMISSION;
CREATE TABLE S1_STAGE_ADMISSION AS SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE FROM NYR_ADMISSION;

ALTER TABLE S1_STAGE_ADMISSION 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_ADMISSION SET DATASOURCE = 'NYR';

ALTER TABLE S1_STAGE_ADMISSION MODIFY BED_ID NUMBER(5,0);
ALTER TABLE S1_STAGE_ADMISSION MODIFY ADMISSION_DATE DATE NULL;
ALTER TABLE S1_STAGE_ADMISSION MODIFY BED_ID NULL;

INSERT INTO S1_STAGE_ADMISSION (SELECT R.RESERVATION_ID, B.BED_NO, R.ADMISSION_DATE, 'WYR'
FROM WYR_RESERVATION R
LEFT JOIN WYR_BEDASSIGNED B  ON R.RESERVATION_ID = B.RESERVATION_ID);

SELECT * FROM S1_STAGE_ADMISSION;

ALTER TABLE S1_STAGE_WARD 
ADD WARD_N_ID VARCHAR2(8);
UPDATE S1_STAGE_WARD SET WARD_N_ID = ( 'W'||'_'|| DATASOURCE ||'_'|| WARD_ID);

ALTER TABLE S1_STAGE_WARD 
ADD CARE_CENTRE_N_ID VARCHAR2(8);
UPDATE S1_STAGE_WARD SET CARE_CENTRE_N_ID = ( 'C'||'_'|| DATASOURCE ||'_'|| CARE_CENTRE_ID);

ALTER TABLE S1_STAGE_BED 
ADD WARD_N_ID VARCHAR2(8);
UPDATE S1_STAGE_BED SET WARD_N_ID = ( 'W'||'_'|| DATASOURCE ||'_'|| WARD_ID);

