DROP table STAGE2_CARE_HOME;
CREATE TABLE STAGE2_CARE_HOME  AS
SELECT SA.BED_ID, B.WARD_N_ID, SA.ADMISSION_DATE AS ADM_MONTH, SA.ADDMISSION_YEAR AS ADM_YEAR FROM S3_STAGE_ADMISSION SA, S1_STAGE_BED B WHERE SA.BED_ID = B.BED_ID;

DROP table STAGE3_CARE_HOME;
CREATE TABLE STAGE3_CARE_HOME  AS
SELECT S2.BED_ID, W.WARD_N_ID,W.CARE_CENTRE_N_ID,W.WARD_NAME, S2.ADM_MONTH, S2.ADM_YEAR FROM STAGE2_CARE_HOME S2, S1_STAGE_WARD W WHERE S2.WARD_N_ID = W.WARD_N_ID;

DROP table STAGE4_CARE_HOME;
CREATE TABLE STAGE4_CARE_HOME  AS
SELECT S3.BED_ID, S3.WARD_N_ID, S3.WARD_NAME, S3.CARE_CENTRE_N_ID, CC.CARE_CENTRE_NAME, S3.ADM_MONTH, S3.ADM_YEAR 
    FROM STAGE3_CARE_HOME S3, S2_STAGE_CARE_CENTRE CC 
        WHERE S3.CARE_CENTRE_N_ID = CC.CARE_CENTRE_N_ID;

DROP TABLE STAGE5_CARE_HOME;
CREATE TABLE STAGE5_CARE_HOME  AS
SELECT  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR, COUNT(*) as BED_OCC 
    FROM  STAGE4_CARE_HOME 
        GROUP by  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR;

