DROP TABLE TEMP_TIME;
CREATE TABLE TEMP_TIME AS 
    SELECT  DISTINCT(ADMISSION_DATE) AS ADD_MONTH,ADDMISSION_YEAR AS ADD_YEAR 
        FROM S3_STAGE_ADMISSION 
            GROUP BY ADMISSION_DATE,ADDMISSION_YEAR;
SELECT * FROM TEMP_TIME;

SELECT * FROM TIME_DIME;
DELETE FROM TIME_DIME;
INSERT INTO  TIME_DIME (SELECT TIME_ID_SEQU.NEXTVAL,ADD_MONTH,ADD_YEAR  FROM TEMP_TIME);

DROP TABLE tmp_ward;
CREATE TABLE tmp_ward AS SELECT DISTINCT WARD_NAME FROM S1_STAGE_WARD;
DELETE FROM WARD_DIME;
INSERT INTO WARD_DIME SELECT WARD_ID_SEQU.NEXTVAL, WARD_NAME FROM tmp_ward;
DELETE FROM CARE_CENTRE_DIME;

INSERT INTO CARE_CENTRE_DIME (
    CARE_CENTRE_ID,
    CARE_CENTRE_NAME,
    START_DATE,
    END_DATE,
    ISCURRENT,
    CARE_CENTRE_N_ID
)
SELECT
    CARE_CENTRE_ID_SEQU.NEXTVAL,
    S.CARE_CENTRE_NAME,
    SYSDATE,
    null,
    'Yes',
    S.CARE_CENTRE_N_ID
FROM
    S2_STAGE_CARE_CENTRE S;
