--DROP TABLE STAGE5_CARE_HOME;
--CREATE TABLE STAGE5_CARE_HOME  AS
--SELECT  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR, COUNT(*) as BED_OCC 
  --  FROM  STAGE4_CARE_HOME 
    --    GROUP by  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR;


INSERT INTO BED_OCC_FACT (BED_OCC_FACT_ID, WARD_ID, TIME_ID , CARE_CENTRE_ID, TOTAL_OCCUPIED_BEDS)
SELECT BED_OCC_FACT_ID_SEQU.NEXTVAL, W.WARD_ID,TD.TIME_ID, CC.CARE_CENTRE_ID, S.BED_OCC
FROM STAGE5_CARE_HOME S, TIME_DIME TD, CARE_CENTRE_DIME CC, WARD_DIME W
WHERE TD.MONTH = S.ADM_MONTH AND S.WARD_NAME = W.WARD_NAME AND S.ADM_YEAR=TD.YEAR AND CC.CARE_CENTRE_NAME = S.CARE_CENTRE_NAME;
