SELECT CARE_CENTRE_ID, CARE_CENTRE_NAME FROM NYR_CARE_CENTRE;
SELECT CARE_ID, CARE_CENTRE_NAME FROM WYR_CARE_CENTRE;

DROP TABLE S1_STAGE_CARE_CENTRE;
CREATE TABLE S1_STAGE_CARE_CENTRE AS SELECT CARE_CENTRE_ID, CARE_CENTRE_NAME FROM NYR_CARE_CENTRE;

ALTER TABLE S1_STAGE_CARE_CENTRE 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_CARE_CENTRE SET DATASOURCE = 'NYR';

INSERT INTO  S1_STAGE_CARE_CENTRE (SELECT CARE_ID, CARE_CENTRE_NAME, 'WYR' FROM WYR_CARE_CENTRE);

SELECT * FROM S1_STAGE_CARE_CENTRE;
DROP TABLE S2_STAGE_CARE_CENTRE;
CREATE TABLE S2_STAGE_CARE_CENTRE AS 
    SELECT ( CC.DATASOURCE || '_' || CC.CARE_CENTRE_ID) AS CARE_CENTRE_N_ID,CARE_CENTRE_ID, CC.CARE_CENTRE_NAME 
        FROM S1_STAGE_CARE_CENTRE CC;
SELECT * FROM S2_STAGE_CARE_CENTRE;
UPDATE S2_STAGE_CARE_CENTRE SET CARE_CENTRE_N_ID = ( 'C'||'_'|| CARE_CENTRE_N_ID);

SELECT WARD_ID, WARD_NAME, CARE_CENTRE_ID FROM NYR_WARD;
SELECT CARE_ID, WARD_NO, WARD_NAME FROM WYR_WARD;

DROP TABLE S1_STAGE_WARD;
CREATE TABLE S1_STAGE_WARD AS SELECT WARD_ID, WARD_NAME, CARE_CENTRE_ID FROM NYR_WARD;

ALTER TABLE S1_STAGE_WARD 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_WARD SET DATASOURCE = 'NYR';

INSERT INTO  S1_STAGE_WARD (SELECT WARD_NO, WARD_NAME, CARE_ID, 'WYR' FROM WYR_WARD);

SELECT * FROM S1_STAGE_WARD;

SELECT BED_ID, WARD_ID FROM NYR_BED;
SELECT BED_NO, WARD_NO FROM WYR_BED;

DROP TABLE S1_STAGE_BED;
CREATE TABLE S1_STAGE_BED AS SELECT BED_ID, WARD_ID FROM NYR_BED;

ALTER TABLE S1_STAGE_BED 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_BED SET DATASOURCE = 'NYR';

ALTER TABLE S1_STAGE_BED MODIFY BED_ID NUMBER(5,0);
ALTER TABLE S1_STAGE_BED MODIFY WARD_ID NUMBER(5,0);

INSERT INTO  S1_STAGE_BED (SELECT BED_NO, WARD_NO, 'WYR' FROM WYR_BED);

SELECT * FROM S1_STAGE_BED;

SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE FROM NYR_ADMISSION;
SELECT RESERVATION_ID, BED_NO FROM WYR_BEDASSIGNED;
SELECT RESERVATION_ID, ADMISSION_DATE FROM WYR_RESERVATION;

DROP TABLE S1_STAGE_ADMISSION;
CREATE TABLE S1_STAGE_ADMISSION AS SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE FROM NYR_ADMISSION;

ALTER TABLE S1_STAGE_ADMISSION 
ADD DATASOURCE VARCHAR2(5);
UPDATE S1_STAGE_ADMISSION SET DATASOURCE = 'NYR';

ALTER TABLE S1_STAGE_ADMISSION MODIFY BED_ID NUMBER(5,0);
ALTER TABLE S1_STAGE_ADMISSION MODIFY ADMISSION_DATE DATE NULL;
ALTER TABLE S1_STAGE_ADMISSION MODIFY BED_ID NULL;

INSERT INTO S1_STAGE_ADMISSION (SELECT R.RESERVATION_ID, B.BED_NO, R.ADMISSION_DATE, 'WYR'
FROM WYR_RESERVATION R
LEFT JOIN WYR_BEDASSIGNED B  ON R.RESERVATION_ID = B.RESERVATION_ID);

SELECT * FROM S1_STAGE_ADMISSION;

ALTER TABLE S1_STAGE_WARD 
ADD WARD_N_ID VARCHAR2(8);
UPDATE S1_STAGE_WARD SET WARD_N_ID = ( 'W'||'_'|| DATASOURCE ||'_'|| WARD_ID);

ALTER TABLE S1_STAGE_WARD 
ADD CARE_CENTRE_N_ID VARCHAR2(8);
UPDATE S1_STAGE_WARD SET CARE_CENTRE_N_ID = ( 'C'||'_'|| DATASOURCE ||'_'|| CARE_CENTRE_ID);

ALTER TABLE S1_STAGE_BED 
ADD WARD_N_ID VARCHAR2(8);
UPDATE S1_STAGE_BED SET WARD_N_ID = ( 'W'||'_'|| DATASOURCE ||'_'|| WARD_ID);

UPDATE S1_STAGE_WARD SET WARD_NAME = 'General Care' WHERE WARD_NAME ='GENERAL care';
UPDATE S1_STAGE_WARD SET WARD_NAME = 'General Ward' WHERE WARD_NAME ='GENERAL WARD';

UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'Altorn Care Home' WHERE CARE_CENTRE_NAME ='ALTORN CareHome';
UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'Bewan Care Home' WHERE CARE_CENTRE_NAME ='BEWAN CareHome';
UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'Wwllbeing Care Home' WHERE CARE_CENTRE_NAME ='WELLBEING CareHome';
UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'LBU Care Home' WHERE CARE_CENTRE_NAME ='LBU CareHome';
UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'Oscar Care Home' WHERE CARE_CENTRE_NAME ='OSCAR CareHome';
UPDATE S1_STAGE_CARE_CENTRE SET CARE_CENTRE_NAME = 'Juno Care Home' WHERE CARE_CENTRE_NAME ='JUNO CareHome';

DELETE FROM S1_STAGE_ADMISSION WHERE ADMISSION_DATE IS null;

SELECT * FROM S1_STAGE_CARE_CENTRE;
DROP TABLE S2_STAGE_CARE_CENTRE;
CREATE TABLE S2_STAGE_CARE_CENTRE AS 
    SELECT ( CC.DATASOURCE || '_' || CC.CARE_CENTRE_ID) AS CARE_CENTRE_N_ID,CARE_CENTRE_ID, CC.CARE_CENTRE_NAME 
        FROM S1_STAGE_CARE_CENTRE CC;
SELECT * FROM S2_STAGE_CARE_CENTRE;
UPDATE S2_STAGE_CARE_CENTRE SET CARE_CENTRE_N_ID = ( 'C'||'_'|| CARE_CENTRE_N_ID);

SELECT * FROM S1_STAGE_ADMISSION;

DROP TABLE S2_STAGE_ADMISSION;
CREATE TABLE S2_STAGE_ADMISSION AS 
    SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE, DATASOURCE 
        FROM S1_STAGE_ADMISSION;
SELECT * FROM S2_STAGE_ADMISSION;
DELETE FROM S2_STAGE_ADMISSION;

ALTER TABLE S2_STAGE_ADMISSION MODIFY ADMISSION_DATE VARCHAR(10);

INSERT INTO S2_STAGE_ADMISSION (SELECT ADMISSION_NO, BED_ID, TO_CHAR(ADMISSION_DATE, 'MM/YYYY'), DATASOURCE FROM S1_STAGE_ADMISSION);
SELECT * FROM S2_STAGE_ADMISSION;

DROP TABLE S3_STAGE_ADMISSION;
CREATE TABLE S3_STAGE_ADMISSION AS SELECT ADMISSION_NO, BED_ID, ADMISSION_DATE, DATASOURCE FROM S1_STAGE_ADMISSION;

ALTER TABLE S3_STAGE_ADMISSION 
ADD ADDMISSION_YEAR VARCHAR2(5);
SELECT * FROM S3_STAGE_ADMISSION;

DELETE FROM S3_STAGE_ADMISSION;

ALTER TABLE S3_STAGE_ADMISSION MODIFY ADMISSION_DATE VARCHAR(5);

INSERT INTO  S3_STAGE_ADMISSION (SELECT ADMISSION_NO, BED_ID, TO_CHAR(ADMISSION_DATE, 'MM'),DATASOURCE,TO_CHAR(ADMISSION_DATE, 'YYYY')  FROM S1_STAGE_ADMISSION);

DROP table STAGE2_CARE_HOME;
CREATE TABLE STAGE2_CARE_HOME  AS
SELECT SA.BED_ID, B.WARD_N_ID, SA.ADMISSION_DATE AS ADM_MONTH, SA.ADDMISSION_YEAR AS ADM_YEAR FROM S3_STAGE_ADMISSION SA, S1_STAGE_BED B WHERE SA.BED_ID = B.BED_ID;

DROP table STAGE3_CARE_HOME;
CREATE TABLE STAGE3_CARE_HOME  AS
SELECT S2.BED_ID, W.WARD_N_ID,W.CARE_CENTRE_N_ID,W.WARD_NAME, S2.ADM_MONTH, S2.ADM_YEAR FROM STAGE2_CARE_HOME S2, S1_STAGE_WARD W WHERE S2.WARD_N_ID = W.WARD_N_ID;

DROP table STAGE4_CARE_HOME;
CREATE TABLE STAGE4_CARE_HOME  AS
SELECT S3.BED_ID, S3.WARD_N_ID, S3.WARD_NAME, S3.CARE_CENTRE_N_ID, CC.CARE_CENTRE_NAME, S3.ADM_MONTH, S3.ADM_YEAR 
    FROM STAGE3_CARE_HOME S3, S2_STAGE_CARE_CENTRE CC 
        WHERE S3.CARE_CENTRE_N_ID = CC.CARE_CENTRE_N_ID;

DROP TABLE STAGE5_CARE_HOME;
CREATE TABLE STAGE5_CARE_HOME  AS
SELECT  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR, COUNT(*) as BED_OCC 
    FROM  STAGE4_CARE_HOME 
        GROUP by  WARD_N_ID,WARD_NAME, CARE_CENTRE_N_ID, CARE_CENTRE_NAME, ADM_MONTH,ADM_YEAR;

------------------------------------------------------------------

INSERT INTO CARE_CENTRE_DIME (
    CARE_CENTRE_ID,
    CARE_CENTRE_NAME,
    START_DATE,
    END_DATE,
    ISCURRENT,
    CARE_CENTRE_N_ID
)
SELECT
    CARE_CENTRE_ID_SEQU.NEXTVAL,
    S.CARE_CENTRE_NAME,
    SYSDATE,
    NULL,
    'Yes',
    S.CARE_CENTRE_N_ID
FROM
    S2_STAGE_CARE_CENTRE S
WHERE
    S.CARE_CENTRE_N_ID IN (
        SELECT CARE_CENTRE_N_ID FROM CARE_CENTRE_DIME CD
        WHERE CD.CARE_CENTRE_N_ID = S.CARE_CENTRE_N_ID
        AND CD.CARE_CENTRE_NAME != S.CARE_CENTRE_NAME
        AND CD.ISCURRENT = 'Yes'
    );

-- UPDATE EXISTING RECORDS TO MARK THEM AS HISTORICAL
UPDATE CARE_CENTRE_DIME
SET
    ISCURRENT = 'No',
    END_DATE = SYSDATE
WHERE
    CARE_CENTRE_NAME IN (
        SELECT CD.CARE_CENTRE_NAME FROM CARE_CENTRE_DIME CD, S2_STAGE_CARE_CENTRE S
        WHERE CD.CARE_CENTRE_N_ID = S.CARE_CENTRE_N_ID
        AND CD.CARE_CENTRE_NAME != S.CARE_CENTRE_NAME
        AND CD.ISCURRENT = 'Yes'
    );

DELETE FROM BED_OCC_FACT;

DROP SEQUENCE BED_OCC_FACT_ID_SEQU;
CREATE SEQUENCE BED_OCC_FACT_ID_SEQU
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    MINVALUE 1;

INSERT INTO BED_OCC_FACT (BED_OCC_FACT_ID, WARD_ID, TIME_ID , CARE_CENTRE_ID, TOTAL_OCCUPIED_BEDS)
SELECT BED_OCC_FACT_ID_SEQU.NEXTVAL, W.WARD_ID,TD.TIME_ID, CC.CARE_CENTRE_ID, S.BED_OCC
FROM STAGE5_CARE_HOME S, TIME_DIME TD, CARE_CENTRE_DIME CC, WARD_DIME W
WHERE TD.MONTH = S.ADM_MONTH AND S.WARD_NAME = W.WARD_NAME AND S.ADM_YEAR=TD.YEAR AND CC.CARE_CENTRE_NAME = S.CARE_CENTRE_NAME AND CC.ISCURRENT = 'Yes';